### ISSUE TITLE
[Bug] docid ray transformation errors when running on colab (release 0.2.2dev1)

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#719]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/universal/doc_id

### What happened + What you expected to happen

Ray version of docid transformation fails on colab with the following error

[full error](https://gist.github.com/sujee/2c39ffbb422ce3e3a3ef6f264aa8ee96)

```
(orchestrate pid=5751) created [Actor(RayTransformFileProcessor, 37cbb100b21c9012ce68444101000000), Actor(RayTransformFileProcessor, e063fda8d2ea6f56efc152e201000000)], alive [ActorState(actor_id='37cbb100b21c9012ce68444101000000', class_name='RayTransformFileProcessor', state='ALIVE', job_id='01000000', name='', node_id='08deddebac466e0100f6c1015c266849f52c8ff173595c8170cdee12', pid=5915, ray_namespace='aa965802-2b25-4b0b-83c8-3e939d83ab34', serialized_runtime_env=None, required_resources=None, death_cause=None, is_detached=None, placement_group_id=None, repr_name=None)]
(orchestrate pid=5751) Traceback (most recent call last):
(orchestrate pid=5751)   File "/usr/local/lib/python3.10/dist-packages/data_processing_ray/runtime/ray/transform_orchestrator.py", line 89, in orchestrate
(orchestrate pid=5751)     processors = RayUtils.create_actors(
(orchestrate pid=5751)   File "/usr/local/lib/python3.10/dist-packages/data_processing_ray/runtime/ray/ray_utils.py", line 121, in create_actors
(orchestrate pid=5751)     raise UnrecoverableException(f"out of {len(actors)} created actors only {len(alive)} alive")
(orchestrate pid=5751) data_processing.utils.unrecoverable.UnrecoverableException: out of 2 created actors only 1 alive
(orchestrate pid=5751) 05:26:08 ERROR - Exception during execution out of 2 created actors only 1 alive: None
(orchestrate pid=5751) Traceback (most recent call last):
(orchestrate pid=5751)   File "/usr/local/lib/python3.10/dist-packages/data_processing_ray/runtime/ray/transform_orchestrator.py", line 138, in orchestrate
(orchestrate pid=5751)     stats["processing_time"] = round(stats["processing_time"], 3)
(orchestrate pid=5751) KeyError: 'processing_time'
(orchestrate pid=5751) 05:26:08 ERROR - Exception during execution 'processing_time': None
05:26:18 INFO - Completed execution in 2.309 min, execution result 1
INFO:data_processing_ray.runtime.ray.transform_launcher:Completed execution in 2.309 min, execution result 1
```

### Reproduction script

[code](https://github.com/sujee/data-prep-kit/blob/intro-example1/examples/notebooks/intro/dpk_intro_1_ray.ipynb)

[colab link](https://colab.research.google.com/github/sujee/data-prep-kit/blob/intro-example1/examples/notebooks/intro/dpk_intro_1_python.ipynb)

error happens on step 5.2

Works with release 0.2.1

```bash
pip install  --default-timeout=100  \
        data-prep-toolkit-transforms==0.2.1 \
        data-prep-toolkit-transforms-ray==0.2.1 \
        deepsearch-toolkit
```

Fails with release 0.2.2.dev1

```bash
pip install  --default-timeout=100  \
        data-prep-toolkit[ray]==0.2.2.dev1 \
        data-prep-toolkit-transforms[ray,all]==0.2.2.dev1 \
        deepsearch-toolkit

```

### OS

Other

### Python

3.11.x

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by shivdeep-singh-ibm** [comment]
The issue seems to be due to lack of resources available to ray to run multiple actors. On colab if the runtime is `CPU` we get only 2 CPUs.
You can change runtime type to TPU( `Runtime-> Change Runtime Type->TPU` ), it can get more CPUs for ray to run.

**Comment by sujee** [comment]
@shivdeep-singh-ibm 
I am running with these ray settings

```
RAY_RUNTIME_WORKERS = 2
RAY_NUM_CPUS =  0.3
RAY_MEMORY_GB = 2  # GB
```

shouldn't we limit our resource usage within these parameters?  Are extra actors being spun up, and running out of CPU cores?

**Comment by blublinsky** [comment]
@shivdeep-singh-ibm  is correct, we added more rigorous checks. just run with 1 worker and you will be fine. But in general using 2 cpus is too low. I would use at least 4.

**Comment by Bytes-Explorer** [comment]
@sujee Can you try the suggestions and let us know if it works?

**Comment by shahrokhDaijavad** [comment]
@sujee and @touma-I I tested docid in the intro example, as is, on Colab today, i.e., with the setting: 
MY_CONFIG.RAY_RUNTIME_WORKERS: 2
MY_CONFIG.RAY_NUM_CPUS: 0.3
MY_CONFIG.RAY_MEMORY_GB: 2
and did not see any error with the docid ray transformation on Colab. 

Did the error happen when running docid in the RAG example? I thought the setting below was just for the pdf2pq transform in that example. 
MY_CONFIG.RAY_RUNTIME_WORKERS = 1

I am going to test this again, when we have solved the bug with pdf2parquet in 0.2.2.dev2

**Comment by daw3rd** [comment]
I expect this was fixed with #721. 
@shahrokhDaijavad can you verify?

**Comment by shahrokhDaijavad** [comment]
@daw3rd  I verified this, so I am closing the issue. 
@daw3rd Update: I just tested this again (because of what @sujee reorted in #722 ) and it fails with the default ray settings on Google Colab. I reopened the issue. Either we have to play with the ray settings to see if we can get it working (considering limitations of Colab with the number of CPUs, etc), or now that we have a python version of fdedup, change the Colab example not to use ray.

**Comment by sujee** [comment]
@shahrokhDaijavad agreed.
Let's focus on pure python versions on colab
