### ISSUE TITLE
[Bug] one of the created Ray actors die during docid transform

### ISSUE THREAD

**Issue by sujee** [data-prep-kit/data-prep-kit#722]
### Search before asking

- [X] I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.

### Component

Transforms/universal/doc_id

### What happened + What you expected to happen

Could be related #719

[full error](https://gist.github.com/sujee/2c39ffbb422ce3e3a3ef6f264aa8ee96)

```
(orchestrate pid=5751) created [Actor(RayTransformFileProcessor, 37cbb100b21c9012ce68444101000000), Actor(RayTransformFileProcessor, e063fda8d2ea6f56efc152e201000000)], alive [ActorState(actor_id='37cbb100b21c9012ce68444101000000', class_name='RayTransformFileProcessor', state='ALIVE', job_id='01000000', name='', node_id='08deddebac466e0100f6c1015c266849f52c8ff173595c8170cdee12', pid=5915, ray_namespace='aa965802-2b25-4b0b-83c8-3e939d83ab34', serialized_runtime_env=None, required_resources=None, death_cause=None, is_detached=None, placement_group_id=None, repr_name=None)]
(orchestrate pid=5751) Traceback (most recent call last):
(orchestrate pid=5751)   File "/usr/local/lib/python3.10/dist-packages/data_processing_ray/runtime/ray/transform_orchestrator.py", line 89, in orchestrate
(orchestrate pid=5751)     processors = RayUtils.create_actors(
(orchestrate pid=5751)   File "/usr/local/lib/python3.10/dist-packages/data_processing_ray/runtime/ray/ray_utils.py", line 121, in create_actors
(orchestrate pid=5751)     raise UnrecoverableException(f"out of {len(actors)} created actors only {len(alive)} alive")
(orchestrate pid=5751) data_processing.utils.unrecoverable.UnrecoverableException: out of 2 created actors only 1 alive
(orchestrate pid=5751) 05:26:08 ERROR - Exception during execution out of 2 created actors only 1 alive: None
(orchestrate pid=5751) Traceback (most recent call last):
(orchestrate pid=5751)   File "/usr/local/lib/python3.10/dist-packages/data_processing_ray/runtime/ray/transform_orchestrator.py", line 138, in orchestrate
(orchestrate pid=5751)     stats["processing_time"] = round(stats["processing_time"], 3)
(orchestrate pid=5751) KeyError: 'processing_time'
(orchestrate pid=5751) 05:26:08 ERROR - Exception during execution 'processing_time': None
05:26:18 INFO - Completed execution in 2.309 min, execution result 1
INFO:data_processing_ray.runtime.ray.transform_launcher:Completed execution in 2.309 min, execution result 1
```

### Reproduction script

[code](https://github.com/sujee/data-prep-kit/blob/intro-example1/examples/notebooks/intro/dpk_intro_1_ray.ipynb)

[colab link](https://colab.research.google.com/github/sujee/data-prep-kit/blob/intro-example1/examples/notebooks/intro/dpk_intro_1_python.ipynb)

error happens on step 5.2

Works with release 0.2.1

```bash
pip install  --default-timeout=100  \
        data-prep-toolkit-transforms==0.2.1 \
        data-prep-toolkit-transforms-ray==0.2.1 \
        deepsearch-toolkit
```

Fails with release 0.2.2.dev1

```bash
pip install  --default-timeout=100  \
        data-prep-toolkit[ray]==0.2.2.dev1 \
        data-prep-toolkit-transforms[ray,all]==0.2.2.dev1 \
        deepsearch-toolkit

```

### OS

Other

### Python

Other

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by daw3rd** [comment]
Based on the logged exception this seems to be a duplicate of #719 and is fixed in PR #721 that has been merged.

**Comment by daw3rd** [comment]
@sujee can you verify the fix with 0.2.2?

**Comment by sujee** [comment]
code : https://colab.research.google.com/github/sujee/data-prep-kit-examples/blob/main/dpk-intro/process_pdfs_1_ray.ipynb

tried with 0.2.2
Error at step 5.2 (docid ray transform)

@shahrokhDaijavad can you verify please?  thx

**Comment by shahrokhDaijavad** [comment]
@sujee I just tested this again and it fails with the default ray settings on Google Colab at step 5.2 (as you reported above). Either we have to play with the ray settings to see if we can get it working (considering the limitations of Colab with the number of CPUs, etc), or now that we have a python version of fdedup in 0.2.3 release, change the Colab example to use python and not ray.
